/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.1 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Oct 22 14:39:49 2013
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


