include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y	+=  mt65xx_lcm_list.o

#LGE_BSP_COMMON sangcheol.seo@lge.com LCD_PORTING
#obj-y	+=  nt35510_dsi_cmd_6572.o
obj-y	+=  ili9340d_dbi_qvga.o
